# 1. Reindirizzamento automatico da HTTP (80) a HTTPS (443)
server {
    listen 80;
    server_name jenkins.devplatform.local;
    return 301 https://$host$request_uri;
}

# 2. Configurazione HTTPS (443)
server {
    listen 443 ssl;
    server_name jenkins.devplatform.local;
    
    # Percorsi dei certificati DENTRO il container Nginx
    ssl_certificate /etc/nginx/certs/jenkins.crt;
    ssl_certificate_key /etc/nginx/certs/jenkins.key;

    # Configurazioni di sicurezza SSL standard (opzionali ma consigliate)
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        # Invia il traffico al container Jenkins sulla rete interna
        proxy_pass http://jenkins:8080;

	# Header fondamentali per far capire a Jenkins che sta girando sotto HTTPS
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Jenkins usa WebSocket per alcune funzionalità (es. Blue Ocean, log live)
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_read_timeout 90s;
    }
}
